In [103]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle

In [104]:
data = pd.read_csv("student/student-mat.csv", sep=";")

In [105]:
print(data.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]


In [106]:
data = data[["G1", "G2", "G3", "studytime", "failures", "internet", "absences"]]
data.internet[data.internet =='yes'] =1
data.internet[data.internet =='no'] =0

C:\anaconda\envs\StockNewsAnalysis\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [107]:
print(data.head())

   G1  G2  G3  studytime  failures internet  absences
0   5   6   6          2         0        0         6
1   5   5   6          2         0        1         4
2   7   8  10          2         3        1        10
3  15  14  15          3         0        1         2
4   6  10  10          2         0        0         4


In [108]:
predict = "G3"

X = np.array(data.drop([predict], 1)) # Features
y = np.array(data[predict]) # Labels

In [109]:
print(X)

[[5 6 2 0 0 6]
 [5 5 2 0 1 4]
 [7 8 2 3 1 10]
 ...
 [10 8 1 3 0 3]
 [11 12 1 0 1 0]
 [8 9 1 0 1 5]]


In [110]:
print(y)

[ 6  6 10 15 10 15 11  6 19 15  9 12 14 11 16 14 14 10  5 10 15 15 16 12
  8  8 11 15 11 11 12 17 16 12 15  6 18 15 11 13 11 12 18 11  9  6 11 20
 14  7 13 13 10 11 13 10 15 15  9 16 11 11  9  9 10 15 12  6  8 16 15 10
  5 14 11 10 10 11 10  5 12 11  6 15 10  8  6 14 10  7  8 18  6 10 14 10
 15 10 14  8  5 17 14  6 18 11  8 18 13 16 19 10 13 19  9 16 14 13  8 13
 15 15 13 13  8 12 11  9  0 18  0  0 12 11  0  0  0  0 12 15  0  9 11 13
  0 11  0 11  0 10  0 14 10  0 12  8 13 10 15 12  0  7  0 10  7 12 10 16
  0 14  0 16 10  0  9  9 11  6  9 11  8 12 17  8 12 11 11 15  9 10 13  9
  8 10 14 15 16 10 18 10 16 10 10  6 11  9  7 13 10  7  8 13 14  8 10 15
  4  8  8 10  6  0 17 13 14  7 15 12  9 12 14 11  9 13  6 10 13 12 11  0
 12 12  0 12  0 18 13  8  5 15  8 10  8  8 12  8 13 11 14  0 18  8 12  9
  0 17 10 11 10  0  9 14 11 14 10 12  9  9  8 10  8 10 12 10 11 11 19 12
 14 15 11 15 13 18 14 11  0  8 14 16 11 10 14 18 13 12 18  8 12 10  0 13
 11 11 13 11  0  9 10 11 13  9 11 15 15 11 16 10  9

In [111]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

In [112]:
linear = linear_model.LinearRegression()

In [113]:
linear.fit(x_train, y_train)
acc = linear.score(x_test, y_test) # acc stands for accuracy 

In [114]:
print(acc)

0.7361041917259701


In [115]:
print('Coefficient: \n', linear.coef_) # These are each slope value
print('Intercept: \n', linear.intercept_) # This is the intercept

Coefficient: 
 [ 0.14807389  0.97746456 -0.14589152 -0.30203589 -0.32252176  0.03633802]
Intercept: 
 -1.2155845663460916


In [116]:
predictions = linear.predict(x_test) # Gets a list of all predictions

for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])

6.7697521262166696 [9 7 2 1 1 20] 8
12.713198544466744 [11 13 1 1 1 10] 13
9.719460513214724 [11 10 1 0 1 0] 10
13.92710947506177 [14 14 3 0 1 4] 14
7.47056598612992 [10 8 2 0 1 0] 9
13.038442094516597 [12 13 1 1 0 6] 14
7.857917371072439 [7 9 3 0 1 0] 8
16.251401840087492 [16 16 2 0 1 2] 17
4.6880933544765035 [8 6 2 2 1 2] 5
13.31084278634647 [13 13 2 0 1 14] 14
8.966235996941672 [10 10 3 2 1 8] 10
10.797078632957062 [10 11 4 0 0 10] 11
8.4480305474269 [10 9 2 0 1 0] 0
8.981273450928455 [7 10 2 0 1 0] 11
9.10483676929494 [11 9 2 0 1 14] 9
6.1210163924511525 [7 7 3 0 1 6] 7
8.547080583654001 [8 9 2 0 0 2] 10
14.221074879552614 [15 14 2 0 1 4] 14
12.721808455146522 [10 13 1 0 1 6] 13
12.910585099819318 [13 13 3 0 1 7] 14
7.320309732825342 [8 8 1 0 1 0] 11
11.42640734437063 [12 11 1 0 1 16] 11
7.465122406229865 [8 8 2 0 1 8] 6
15.20126123079962 [16 15 2 0 1 0] 15
9.794318928578386 [12 10 2 0 1 2] 11
13.52194763121182 [12 14 3 0 1 1] 15
11.964554405194987 [11 12 2 0 1 12] 11
6.69946266710

In [117]:
print(x_test)

[[9 7 2 1 1 20]
 [11 13 1 1 1 10]
 [11 10 1 0 1 0]
 [14 14 3 0 1 4]
 [10 8 2 0 1 0]
 [12 13 1 1 0 6]
 [7 9 3 0 1 0]
 [16 16 2 0 1 2]
 [8 6 2 2 1 2]
 [13 13 2 0 1 14]
 [10 10 3 2 1 8]
 [10 11 4 0 0 10]
 [10 9 2 0 1 0]
 [7 10 2 0 1 0]
 [11 9 2 0 1 14]
 [7 7 3 0 1 6]
 [8 9 2 0 0 2]
 [15 14 2 0 1 4]
 [10 13 1 0 1 6]
 [13 13 3 0 1 7]
 [8 8 1 0 1 0]
 [12 11 1 0 1 16]
 [8 8 2 0 1 8]
 [16 15 2 0 1 0]
 [12 10 2 0 1 2]
 [12 14 3 0 1 1]
 [11 12 2 0 1 12]
 [6 8 1 3 1 16]
 [6 5 3 1 0 0]
 [12 13 2 0 1 0]
 [10 10 2 0 0 4]
 [10 9 3 0 1 2]
 [16 15 1 0 1 5]
 [10 9 2 0 0 0]
 [9 9 2 1 0 0]
 [6 5 1 1 0 14]
 [13 13 3 0 1 0]
 [5 0 1 3 1 0]
 [10 10 3 0 1 0]
 [12 13 2 0 1 14]]
